name: VAX Stock Pipeline

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pipeline
        env:
          VAX_FTP_HOST: ${{ secrets.VAX_FTP_HOST }}
          VAX_FTP_PORT: ${{ secrets.VAX_FTP_PORT }}
          VAX_FTP_USER: ${{ secrets.VAX_FTP_USER }}
          VAX_FTP_PASS: ${{ secrets.VAX_FTP_PASS }}
        run: python sftp_xml_to_csv_pipeline_vax.py
